name: Backend unit test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

# defaults:
#   run:
#     working-directory: Backend

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    env:
      FLASK_APP: Backend
      FLASK_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and set environment
      run: |
        python -m pip install --upgrade pip
        pip install -r Backend/requirements.txt
    - name: Create database
      run: |
        flask db init
        flask db upgrade
        flask run
    # - name: Run tests
    #   run: |
    #     python test/run_tests.py