name: Frontend unit test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

defaults:
  run:
    working-directory: frontend

jobs:
  build:

    runs-on: ubuntu-18.04
    # strategy:
    #   matrix:
    #     node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
      - name: Run tests
        run: |
          npm test
      - name: Run build
        run: |
          npm run build
